create or replace package pkg_employee_details
Procedure p_add_employee
Procedure p_delete_employee
Procedure p_remove_employee
End pkg_employee_details;

create or replace package body pkg_employee_details
Procedure p_add_employee
Procedure p_delete_employee
Procedure p_remove_employee
End pkg_employee_details;

